* Improve typing, look for Mac native iodbc library

diff --git a/packages/odbc/configure b/packages/odbc/configure
--- a/packages/odbc/configure
+++ b/packages/odbc/configure
@@ -3746,7 +3746,7 @@ else
     CWFLAGS=
 fi
 
-
+havelib=no
 echo "$as_me:$LINENO: checking for SQLAllocEnv in -lodbc" >&5
 echo $ECHO_N "checking for SQLAllocEnv in -lodbc... $ECHO_C" >&6
 if test "${ac_cv_lib_odbc_SQLAllocEnv+set}" = set; then
@@ -3812,11 +3812,77 @@ fi
 echo "$as_me:$LINENO: result: $ac_cv_lib_odbc_SQLAllocEnv" >&5
 echo "${ECHO_T}$ac_cv_lib_odbc_SQLAllocEnv" >&6
 if test $ac_cv_lib_odbc_SQLAllocEnv = yes; then
-  cat >>confdefs.h <<_ACEOF
-#define HAVE_LIBODBC 1
-_ACEOF
+  havelib=yes
+fi
 
-  LIBS="-lodbc $LIBS"
+if test $havelib = no; then
+  echo "$as_me:$LINENO: checking for SQLAllocEnv in -liodbc" >&5
+echo $ECHO_N "checking for SQLAllocEnv in -liodbc... $ECHO_C" >&6
+if test "${ac_cv_lib_iodbc_SQLAllocEnv+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-liodbc  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char SQLAllocEnv ();
+int
+main ()
+{
+SQLAllocEnv ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_iodbc_SQLAllocEnv=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_iodbc_SQLAllocEnv=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_iodbc_SQLAllocEnv" >&5
+echo "${ECHO_T}$ac_cv_lib_iodbc_SQLAllocEnv" >&6
+if test $ac_cv_lib_iodbc_SQLAllocEnv = yes; then
+  havelib=yes
+fi
 
 fi
 
@@ -4150,7 +4216,7 @@ fi
 done
 
 
-if test "$ac_cv_lib_odbc_SQLAllocEnv" = yes &&
+if test "$havelib" = yes &&
    test "$ac_cv_header_sql_h" = yes; then
   TARGETS="odbc4pl.$SO"
 else
