PORT: Compile MacOSX bundle using gcc.
This provides about 40% performance improvement.

diff --git a/scripts/make-distribution b/scripts/make-distribution
--- a/scripts/make-distribution
+++ b/scripts/make-distribution
@@ -7,6 +7,7 @@ fi
 
 version=`cat VERSION`
 pdf_build_dir=build.pdf
+macos_builddir=build.bundle-gcc
 PUBLIC="plweb@oehoe:srv/plweb/data/download/devel"
 export MACOSX_DEPLOYMENT_TARGET=10.15
 
@@ -29,9 +30,10 @@ build_win64()
 }
 
 build_macos_universal_binary()
-{ rm -rf build.macosx-fat
-  mkdir build.macosx-fat
-  ( cd build.macosx-fat
+{ buildir=${1-build.macosx-fat}
+  rm -rf $buildir
+  mkdir $buildir
+  ( cd $buildir
     PREFIX=$HOME/deps
     export PKG_CONFIG_LIBDIR="/usr/lib/pkgconfig:$PREFIX/lib/pkgconfig"
     export CMAKE_PREFIX_PATH="$PREFIX:/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr"
@@ -54,10 +56,67 @@ build_macos_universal_binary()
   )
 }
 
+build_macos_gcc_arch()
+{ arch=$1
+  builddir=$2
+
+  case $arch in
+      arm64)
+	  GCCDIR=/opt/local/bin
+	  ;;
+      x86_64)
+	  GCCDIR=$HOME/x86_64/bin
+	  ;;
+      *)
+	  echo "ERROR: Unknown architecture $arch"
+	  return 1
+  esac
+
+  if [ -z "$builddir" ]; then
+      echo "ERROR: Usage: $0 arch builddir"
+      return 1
+  fi
+
+  rm -rf $builddir
+  mkdir $builddir
+  ( cd $builddir
+    PREFIX=$HOME/deps
+    export PKG_CONFIG_LIBDIR="/usr/lib/pkgconfig:$PREFIX/lib/pkgconfig"
+    export CMAKE_PREFIX_PATH="$PREFIX:/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr"
+    export PATH=$HOME/deps/bin:$GCCDIR:$PATH
+    export CC=gcc-mp-15
+    export CXX=g++-mp-15
+    MACOSX_DEPLOYMENT_TARGET=$MACOSX_DEPLOYMENT_TARGET \
+	cmake -DCMAKE_BUILD_TYPE=PGO \
+	      -DSWIPL_CC=cc -DSWIPL_CXX=c++ \
+	      -DMACOSX_DEPENDENCIES_FROM=$HOME/deps \
+	      -DPKG_CONFIG_EXECUTABLE=/opt/local/bin/pkg-config \
+              -DMACOS_UNIVERSAL_BINARY=ON \
+              -DBUILD_MACOS_BUNDLE=ON \
+	      -DJAVA_COMPATIBILITY=ON \
+	      -DCMAKE_FRAMEWORK_PATH=/Library/Frameworks \
+	      -G Ninja ..
+    ninja
+  )
+}
+
+build_macos_gcc_universal()
+{ buildir=${1-build.fat-gcc}
+  buildir_x86_64=$buildir-x86_64
+  build_macos_gcc_arch x86_64 $buildir_x86_64 || return 1
+  build_macos_gcc_arch arm64 $buildir || return 1
+  ( cd $buildir
+    ../scripts/macos-import-x86_64.sh ../$buildir_x86_64 || return 1
+    cpack
+  )
+}
+
 build_macos_gcc()
-{ rm -rf build.macosx-gcc
-  mkdir build.macosx-gcc
-  ( cd build.macosx-gcc
+{ buildir=${1-build.macosx-gcc}
+
+  rm -rf $builddir
+  mkdir $builddir
+  ( cd $builddir
     PREFIX=$HOME/deps
     export PKG_CONFIG_LIBDIR="/usr/lib/pkgconfig:$PREFIX/lib/pkgconfig"
     export CMAKE_PREFIX_PATH="$PREFIX:/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr"
@@ -130,9 +189,7 @@ list_file()
 
 list_built()
 { if [ $(uname) = Darwin ]; then
-    list_file build.macosx-fat/swipl-${version}-1.fat.dmg
-    list_file build.macosx-gcc/swipl-${version}-1.x86_64.dmg
-    list_file build.macosx/swipl-${version}-1.x86_64.dmg
+    list_file $macos_builddir/swipl-${version}-1.fat.dmg
   else
     ls -l build.win64/swipl-${version}-1.x64.exe
     ls -l build.pdf/man/SWI-Prolog-$version.pdf
@@ -147,9 +204,9 @@ build()
 force_build()
 { if [ $(uname) = Darwin ]; then
     if uname -a | grep arm64 > /dev/null; then
-      build_macos_universal_binary
+      build_macos_gcc_universal $macos_builddir
     else
-      build_macos_gcc
+      build_macos_gcc $macos_builddir
     fi
   else
     build_pdf
@@ -175,15 +232,9 @@ upload_win64()
 }
 
 upload_macosx()
-{ if [ -f build.macosx-fat/swipl-${version}-1.fat.dmg ]; then
-    echo "Uploading universal binary version"
-    upload_file bin build.macosx-fat/swipl-${version}-1.fat.dmg
-  elif [ -f build.macosx-gcc/swipl-${version}-1.x86_64.dmg ]; then
-    echo "Uploading fast GCC version"
-    upload_file bin build.macosx-gcc/swipl-${version}-1.x86_64.dmg
-  else
-    echo "WARNING: uploading slow Clang version"
-    upload_file bin build.macosx/swipl-${version}-1.x86_64.dmg
+{ if [ -f $macos_builddir/swipl-${version}-1.fat.dmg ]; then
+    echo "Uploading MacOS binary version"
+    upload_file bin $macos_builddir/swipl-${version}-1.fat.dmg
   fi
 }
 
