* Make kernel use intptr_t

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -845,8 +845,8 @@ Optional Features:
   --disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
   --enable-runtime	  Runtime system only
-  --enable-mt		  Enable Multi-threading
   --enable-shared	  Prolog kernel as shared obj
+  --disable-mt		  Disable Multi-threading
   --disable-readline	  Do NOT include GNU readline
   --disable-mapped-stacks Do not use mmap for stacks
   --enable-segv-handling  Use SIGSEGV to guard stacks
@@ -2479,21 +2479,6 @@ _ACEOF
 	       esac
 fi;
 
-# Check whether --enable-mt or --disable-mt was given.
-if test "${enable_mt+set}" = set; then
-  enableval="$enable_mt"
-  case "$enableval" in
-		   yes) MT=yes
-
-cat >>confdefs.h <<\_ACEOF
-#define NO_SEGV_HANDLING 1
-_ACEOF
-
-			;;
-		   *)  ;;
-	       esac
-fi;
-
 # Check whether --enable-shared or --disable-shared was given.
 if test "${enable_shared+set}" = set; then
   enableval="$enable_shared"
@@ -2505,6 +2490,26 @@ if test "${enable_shared+set}" = set; then
 		   *)   ;;
 	       esac
 fi;
+
+# Check whether --enable-mt or --disable-mt was given.
+if test "${enable_mt+set}" = set; then
+  enableval="$enable_mt"
+  case "$enableval" in
+		   yes) MT=yes
+			;;
+		   *)  ;;
+	       esac
+else
+  MT=yes
+fi;
+
+if test "x$MT" = "xyes"; then
+
+cat >>confdefs.h <<\_ACEOF
+#define NO_SEGV_HANDLING 1
+_ACEOF
+
+fi
 
 readline_ok=no
 # Check whether --enable-readline or --disable-readline was given.
@@ -10787,6 +10792,64 @@ _ACEOF
 fi
 
 
+echo "$as_me:$LINENO: checking for intptr_t" >&5
+echo $ECHO_N "checking for intptr_t... $ECHO_C" >&6
+if test "${ac_cv_type_intptr_t+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+int
+main ()
+{
+if ((intptr_t *) 0)
+  return 0;
+if (sizeof (intptr_t))
+  return 0;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_type_intptr_t=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_type_intptr_t=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $ac_cv_type_intptr_t" >&5
+echo "${ECHO_T}$ac_cv_type_intptr_t" >&6
+
+
 if test "x$ac_cv_func_unsetenv" = "xyes"; then
   echo "$as_me:$LINENO: checking \"whether unsetenv is void\"" >&5
 echo $ECHO_N "checking \"whether unsetenv is void\"... $ECHO_C" >&6
@@ -13265,16 +13328,16 @@ cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
  main()
-  { long l[10];
+  { intptr_t l[10];
     double *p;
-    unsigned long x = (unsigned long) l;
+    uintptr_t x = (uintptr_t) l;
 
 #if defined(__alpha__) || defined(__alpha) || defined(__ia64__) || defined(__sparc__)
     exit(1);
 #endif
 
     if ( x % sizeof(double) == 0 )
-      x += sizeof(long);
+      x += sizeof(intptr_t);
     p = (double  *) x;
     *p = 1.0;
 
@@ -13293,8 +13356,8 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  echo "$as_me:$LINENO: result: as long" >&5
-echo "${ECHO_T}as long" >&6
+  echo "$as_me:$LINENO: result: as intptr_t" >&5
+echo "${ECHO_T}as intptr_t" >&6
 else
   echo "$as_me: program exited with status $ac_status" >&5
 echo "$as_me: failed program was:" >&5
@@ -13326,15 +13389,15 @@ cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
  main()
-  { char l[sizeof(long)*2];
-    long *p;
+  { char l[sizeof(intptr_t)*2];
+    intptr_t *p;
 
 #if defined(__alpha__) || defined(__alpha) || defined(__ia64__) || defined(__sparc__)
     exit(1);
 #endif
 
     l[0] = 10;
-    p = (long *)(l+1);
+    p = (intptr_t *)(l+1);
     *p = 0x20406080;
 
     if ( l[0] == 10 && *p == 0x20406080 )
