* Check for -pthreads

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -5623,11 +5623,13 @@ _ACEOF
 esac
 
   if test "$GCC" = "yes"; then
-{ echo "$as_me:$LINENO: checking \"whether gcc supports -pthread\"" >&5
-echo $ECHO_N "checking \"whether gcc supports -pthread\"... $ECHO_C" >&6; }
-ocflags="$CFLAGS"
-CFLAGS="$CFLAGS -pthread"
-cat >conftest.$ac_ext <<_ACEOF
+  for PTHREAD in -pthread -pthreads; do
+    if test "$pthread_ok" = "false"; then
+      { echo "$as_me:$LINENO: checking \"whether gcc supports $PTHREAD\"" >&5
+echo $ECHO_N "checking \"whether gcc supports $PTHREAD\"... $ECHO_C" >&6; }
+      ocflags="$CFLAGS"
+      CFLAGS="$CFLAGS $PTHREAD"
+      cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
 cat confdefs.h >>conftest.$ac_ext
@@ -5640,10 +5642,10 @@ int
 main ()
 {
  static pthread_mutex_t m = PTHREAD_MUTEX_INITIALIZER;
-	      pthread_mutex_lock(&m);
-	      pthread_mutex_unlock(&m);
+		    pthread_mutex_lock(&m);
+		    pthread_mutex_unlock(&m);
 #if !(defined(_REENTRANT) || defined(_THREAD_SAFE))
-  this should not be compiled
+	this should not be compiled
 #endif
 
   ;
@@ -5685,21 +5687,23 @@ eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
   pthread_ok=true
-	    CMFLAGS="$CMFLAGS -pthread"
-	    LDFLAGS="$LDFLAGS -pthread"
-	    { echo "$as_me:$LINENO: result: yes" >&5
+		  CMFLAGS="$CMFLAGS $PTHREAD"
+		  LDFLAGS="$LDFLAGS $PTHREAD"
+		  { echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6; }
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
 	CFLAGS="$ocflags"
-	    { echo "$as_me:$LINENO: result: no" >&5
+		  { echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6; }
 fi
 
 rm -f core conftest.err conftest.$ac_objext \
       conftest$ac_exeext conftest.$ac_ext
+      fi
+    done
   fi
 
   if test "$pthread_ok" = "false"; then
@@ -13337,6 +13341,79 @@ fi
 fi
 fi
 
+{ echo "$as_me:$LINENO: checking for sysconf support for _SC_NPROCESSORS_CONF" >&5
+echo $ECHO_N "checking for sysconf support for _SC_NPROCESSORS_CONF... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+ #include <unistd.h>
+int
+main ()
+{
+ long n = sysconf(_SC_NPROCESSORS_CONF);
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag" || test ! -s conftest.err'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_sc_nprocessors_conf="yes"
+   { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	{ echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+
+if test "x$ac_sc_nprocessors_conf" = "xyes"; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_SC_NPROCESSORS_CONF 1
+_ACEOF
+
+else
+
 { echo "$as_me:$LINENO: checking linux /proc/cpuinfo" >&5
 echo $ECHO_N "checking linux /proc/cpuinfo... $ECHO_C" >&6; }
 if grep 'processor	 *: 0' /proc/cpuinfo 2>&1 > /dev/null; then
@@ -13350,6 +13427,7 @@ _ACEOF
 else
    { echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6; }
+fi
 fi
 
 
