* Deal with BeOS flags for creating a shared object

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -8368,7 +8368,7 @@ EOF
 EOF
 
 	cat >>confdefs.h <<\EOF
-#define SO_FORMAT_LDFLAGS "-bundle -bundle_loader \"%s\"", plexe
+#define SO_FORMAT_LDFLAGS "-bundle -bundle_loader \"%s\" -o \"%s\"", plexe, soout
 EOF
 
 	CMFLAGS="-no-cpp-precomp"
@@ -8378,6 +8378,12 @@ EOF
 	SO_LD="dllwrap"
 	SO_pic=""
 	SO_PIC=""
+	;;
+  *beos*)
+	cat >>confdefs.h <<\EOF
+#define SO_FORMAT_LDFLAGS "-nostart -Xlinker -soname=\"%s\"", soout
+EOF
+
 	;;
   *)
 	;;
@@ -8506,7 +8512,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:8509: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:8515: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -8679,7 +8685,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:8682: error: ambiguous option: $1
+    { { echo "$as_me:8688: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -8698,7 +8704,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:8701: error: unrecognized option: $1
+  -*) { { echo "$as_me:8707: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -8735,7 +8741,7 @@ do
   # Handling of arguments.
   "$OutputFiles" ) CONFIG_FILES="$CONFIG_FILES $OutputFiles" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h" ;;
-  *) { { echo "$as_me:8738: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:8744: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -8978,7 +8984,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:8981: creating $ac_file" >&5
+    { echo "$as_me:8987: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -8996,7 +9002,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:8999: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:9005: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -9009,7 +9015,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:9012: error: cannot find input file: $f" >&5
+           { { echo "$as_me:9018: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -9070,7 +9076,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:9073: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:9079: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -9081,7 +9087,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:9084: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:9090: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -9094,7 +9100,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:9097: error: cannot find input file: $f" >&5
+           { { echo "$as_me:9103: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -9211,7 +9217,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:9214: $ac_file is unchanged" >&5
+      { echo "$as_me:9220: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
